name: coach
author: Isaac Jessup
email: ibjessup@gmail.com
url: http://example.com
version: '0.1'
title: 'coach'
icon: futbol-o
dependencies:
    - !!python/object:aj.plugins.PluginDependency {
        plugin_name: core
    }
    - !!python/object:aj.plugins.PluginDependency {
        plugin_name: dashboard
    }
resources:
    - 'resources/js/module.es'
    - 'resources/js/router.es'
    - 'resources/vendor/d3/d3.v3.min.js'
    - 'resources/js/controllers/bootstrap.controller.es'
    - 'resources/js/controllers/fabric.controller.es'
    - 'resources/js/controllers/nodes.controller.es'
    - 'resources/js/controllers/storage.controller.es'
    - 'resources/js/controllers/storage/ceph.controller.es'
    - 'resources/js/controllers/widgets/ceph_pages.controller.es'
    - 'resources/js/services/bootstrap.service.es'
    - 'resources/js/services/fabric.service.es'
    - 'resources/js/services/storage.service.es'
    - 'resources/js/services/storage/ceph.service.es'
    - 'resources/partial/bootstrap.html'
    - 'resources/partial/fabric.html'
    - 'resources/partial/nodes.html'
    - 'resources/partial/storage.html'
    - 'resources/partial/storage/ceph.html'
    - 'resources/partial/widgets/ceph_pages.html'
    - 'resources/partial/widgets/ceph_pages.config.html'
    - 'ng:coach'
